import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profile from "../../public/images/profile/arturprofile-side.png"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image 
                src={profile}
                alt="Artur Serra"
                className="w-full h-auto"
              />
            </div>

            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText text="Crafting reliable solutions with quality code." className=' !text-left'/>
              <p>
              Cybersecurity graduate turned full-stack developer with a knack for blockchain development, focused on building secure and dynamic digital applications.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
